/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SlashesRouteImport } from './routes/slashes'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PhotographyRouteImport } from './routes/photography'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as R404RouteImport } from './routes/404'
import { Route as ShortRouteImport } from './routes/$short'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as ProjectSlugRouteImport } from './routes/project/$slug'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as ApiContactRouteImport } from './routes/api/contact'
import { Route as ApiDashboardSubscribersRouteImport } from './routes/api/dashboard/subscribers'
import { Route as ApiDashboardSubscribeNewsletterRouteImport } from './routes/api/dashboard/subscribe-newsletter'
import { Route as ApiDashboardGithubRouteImport } from './routes/api/dashboard/github'
import { Route as ApiDashboardDevRouteImport } from './routes/api/dashboard/dev'

const SlashesRoute = SlashesRouteImport.update({
  id: '/slashes',
  path: '/slashes',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotographyRoute = PhotographyRouteImport.update({
  id: '/photography',
  path: '/photography',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortRoute = ShortRouteImport.update({
  id: '/$short',
  path: '/$short',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectSlugRoute = ProjectSlugRouteImport.update({
  id: '/project/$slug',
  path: '/project/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardSubscribersRoute = ApiDashboardSubscribersRouteImport.update({
  id: '/api/dashboard/subscribers',
  path: '/api/dashboard/subscribers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardSubscribeNewsletterRoute =
  ApiDashboardSubscribeNewsletterRouteImport.update({
    id: '/api/dashboard/subscribe-newsletter',
    path: '/api/dashboard/subscribe-newsletter',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDashboardGithubRoute = ApiDashboardGithubRouteImport.update({
  id: '/api/dashboard/github',
  path: '/api/dashboard/github',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardDevRoute = ApiDashboardDevRouteImport.update({
  id: '/api/dashboard/dev',
  path: '/api/dashboard/dev',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$short': typeof ShortRoute
  '/404': typeof R404Route
  '/dashboard': typeof DashboardRoute
  '/photography': typeof PhotographyRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/slashes': typeof SlashesRoute
  '/api/contact': typeof ApiContactRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/project/$slug': typeof ProjectSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/api/dashboard/dev': typeof ApiDashboardDevRoute
  '/api/dashboard/github': typeof ApiDashboardGithubRoute
  '/api/dashboard/subscribe-newsletter': typeof ApiDashboardSubscribeNewsletterRoute
  '/api/dashboard/subscribers': typeof ApiDashboardSubscribersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$short': typeof ShortRoute
  '/404': typeof R404Route
  '/dashboard': typeof DashboardRoute
  '/photography': typeof PhotographyRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/slashes': typeof SlashesRoute
  '/api/contact': typeof ApiContactRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/project/$slug': typeof ProjectSlugRoute
  '/blog': typeof BlogIndexRoute
  '/api/dashboard/dev': typeof ApiDashboardDevRoute
  '/api/dashboard/github': typeof ApiDashboardGithubRoute
  '/api/dashboard/subscribe-newsletter': typeof ApiDashboardSubscribeNewsletterRoute
  '/api/dashboard/subscribers': typeof ApiDashboardSubscribersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$short': typeof ShortRoute
  '/404': typeof R404Route
  '/dashboard': typeof DashboardRoute
  '/photography': typeof PhotographyRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/slashes': typeof SlashesRoute
  '/api/contact': typeof ApiContactRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/project/$slug': typeof ProjectSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/api/dashboard/dev': typeof ApiDashboardDevRoute
  '/api/dashboard/github': typeof ApiDashboardGithubRoute
  '/api/dashboard/subscribe-newsletter': typeof ApiDashboardSubscribeNewsletterRoute
  '/api/dashboard/subscribers': typeof ApiDashboardSubscribersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$short'
    | '/404'
    | '/dashboard'
    | '/photography'
    | '/profile'
    | '/projects'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/slashes'
    | '/api/contact'
    | '/blog/$slug'
    | '/project/$slug'
    | '/blog/'
    | '/api/dashboard/dev'
    | '/api/dashboard/github'
    | '/api/dashboard/subscribe-newsletter'
    | '/api/dashboard/subscribers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$short'
    | '/404'
    | '/dashboard'
    | '/photography'
    | '/profile'
    | '/projects'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/slashes'
    | '/api/contact'
    | '/blog/$slug'
    | '/project/$slug'
    | '/blog'
    | '/api/dashboard/dev'
    | '/api/dashboard/github'
    | '/api/dashboard/subscribe-newsletter'
    | '/api/dashboard/subscribers'
  id:
    | '__root__'
    | '/'
    | '/$short'
    | '/404'
    | '/dashboard'
    | '/photography'
    | '/profile'
    | '/projects'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/slashes'
    | '/api/contact'
    | '/blog/$slug'
    | '/project/$slug'
    | '/blog/'
    | '/api/dashboard/dev'
    | '/api/dashboard/github'
    | '/api/dashboard/subscribe-newsletter'
    | '/api/dashboard/subscribers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShortRoute: typeof ShortRoute
  R404Route: typeof R404Route
  DashboardRoute: typeof DashboardRoute
  PhotographyRoute: typeof PhotographyRoute
  ProfileRoute: typeof ProfileRoute
  ProjectsRoute: typeof ProjectsRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SlashesRoute: typeof SlashesRoute
  ApiContactRoute: typeof ApiContactRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ProjectSlugRoute: typeof ProjectSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiDashboardDevRoute: typeof ApiDashboardDevRoute
  ApiDashboardGithubRoute: typeof ApiDashboardGithubRoute
  ApiDashboardSubscribeNewsletterRoute: typeof ApiDashboardSubscribeNewsletterRoute
  ApiDashboardSubscribersRoute: typeof ApiDashboardSubscribersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/slashes': {
      id: '/slashes'
      path: '/slashes'
      fullPath: '/slashes'
      preLoaderRoute: typeof SlashesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photography': {
      id: '/photography'
      path: '/photography'
      fullPath: '/photography'
      preLoaderRoute: typeof PhotographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$short': {
      id: '/$short'
      path: '/$short'
      fullPath: '/$short'
      preLoaderRoute: typeof ShortRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$slug': {
      id: '/project/$slug'
      path: '/project/$slug'
      fullPath: '/project/$slug'
      preLoaderRoute: typeof ProjectSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/subscribers': {
      id: '/api/dashboard/subscribers'
      path: '/api/dashboard/subscribers'
      fullPath: '/api/dashboard/subscribers'
      preLoaderRoute: typeof ApiDashboardSubscribersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/subscribe-newsletter': {
      id: '/api/dashboard/subscribe-newsletter'
      path: '/api/dashboard/subscribe-newsletter'
      fullPath: '/api/dashboard/subscribe-newsletter'
      preLoaderRoute: typeof ApiDashboardSubscribeNewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/github': {
      id: '/api/dashboard/github'
      path: '/api/dashboard/github'
      fullPath: '/api/dashboard/github'
      preLoaderRoute: typeof ApiDashboardGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/dev': {
      id: '/api/dashboard/dev'
      path: '/api/dashboard/dev'
      fullPath: '/api/dashboard/dev'
      preLoaderRoute: typeof ApiDashboardDevRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShortRoute: ShortRoute,
  R404Route: R404Route,
  DashboardRoute: DashboardRoute,
  PhotographyRoute: PhotographyRoute,
  ProfileRoute: ProfileRoute,
  ProjectsRoute: ProjectsRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SlashesRoute: SlashesRoute,
  ApiContactRoute: ApiContactRoute,
  BlogSlugRoute: BlogSlugRoute,
  ProjectSlugRoute: ProjectSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiDashboardDevRoute: ApiDashboardDevRoute,
  ApiDashboardGithubRoute: ApiDashboardGithubRoute,
  ApiDashboardSubscribeNewsletterRoute: ApiDashboardSubscribeNewsletterRoute,
  ApiDashboardSubscribersRoute: ApiDashboardSubscribersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
