// Generated by https://quicktype.io

export interface Photos {
  id: string
  created_at: string
  updated_at: string
  promoted_at: null | string
  width: number
  height: number
  color: string
  blur_hash: string
  description: null | string
  alt_description: null
  urls: Urls
  links: PhotoLinks
  categories: any[]
  likes: number
  liked_by_user: boolean
  current_user_collections: any[]
  sponsorship: Sponsorship | null
  topic_submissions: TopicSubmissions
  user: User
}

export interface PhotoLinks {
  self: string
  html: string
  download: string
  download_location: string
}

export interface Sponsorship {
  impression_urls: string[]
  tagline: string
  tagline_url: string
  sponsor: User
}

export interface User {
  id: string
  updated_at: string
  username: string
  name: string
  first_name: string
  last_name: null | string
  twitter_username: null | string
  portfolio_url: null | string
  bio: null | string
  location: null | string
  links: UserLinks
  profile_image: ProfileImage
  instagram_username: null | string
  total_collections: number
  total_likes: number
  total_photos: number
  accepted_tos: boolean
  for_hire: boolean
  social: Social
}

export interface UserLinks {
  self: string
  html: string
  photos: string
  likes: string
  portfolio: string
  following: string
  followers: string
}

export interface ProfileImage {
  small: string
  medium: string
  large: string
}

export interface Social {
  instagram_username: null | string
  portfolio_url: null | string
  twitter_username: null | string
  paypal_email: null
}

export interface TopicSubmissions {}

export interface Urls {
  raw: string
  full: string
  regular: string
  small: string
  thumb: string
  small_s3: string
}
