// Generated by https://quicktype.io

export interface UnsplashProfile {
  id: string
  username: string
  downloads: Downloads
  views: Downloads
}

export interface Downloads {
  total: number
  historical: Historical
}

export interface Historical {
  change: number
  average: number
  resolution: string
  quantity: number
  values: Value[]
}

export interface Value {
  date: string
  value: number
}
